org: clouding

service: dysls

frameworkVersion: "4"

package: 
  individually: true
  patterns: ['package.json'] 

build:
  esbuild:
    format: esm
    minify: true
    bundle: true
    external:  
      - @aws-sdk/client-s3
    exclude:  
      - @aws-sdk/*
    packages: external
    buildConcurrency: 3
    sourcemap: false

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128

functions:
  hello:
    handler: src/lambdas/hello.handler
    events:
      - httpApi:
          path: /
          method: GET
  listNotes:
    handler: src/lambdas/notes/list-notes.handler
    events:
      - httpApi:
          path: /notes
          method: GET
  getNote:
    handler: src/lambdas/notes/get-note.handler
    events:
      - httpApi:
          path: /notes/{noteId}
          method: GET
  createNote:
    handler: src/lambdas/notes/create-note.handler
    events:
      - httpApi:
          path: /notes
          method: POST
  updateNote:
    handler: src/lambdas/notes/update-note.handler
    events:
      - httpApi:
          path: /notes/{noteId}
          method: PUT
  deleteNote:
    handler: src/lambdas/notes/delete-note.handler
    events:
      - httpApi:
          path: /notes/{noteId}
          method: DELETE
  
resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NotesTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification: 
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH