@baseUrl = https://jk0uw4y143.execute-api.us-east-1.amazonaws.com


###

# @name ping
GET {{baseUrl}}/
Content-Type: application/json

###

# @name list_notes
GET {{baseUrl}}/notes
Content-Type: application/json

###

# @name get_note
GET {{baseUrl}}/notes/ccb7c53a-c5bf-4184-8eec-c898ebd1aeba
Content-Type: application/json

###

# @name create_note
POST {{baseUrl}}/notes
Content-Type: application/json

{
    "content": "content value",
    "tags": ["tag1, tag2"]
}

###

# @name update_note
PUT {{baseUrl}}/notes/273629b8-448f-47e4-ad81-86388f5d7b8b
Content-Type: application/json

{
    "content": "new content value",
    "tags": ["tag1, tag3"]
}

###

# @name delete_note
DELETE {{baseUrl}}/notes/b57c2538-26cd-4e21-8d29-508fa6fab9a9
Content-Type: application/json

